# Generated by Django 2.2 on 2019-07-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_dcdetailcustomer_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetailcustomer',
            name='serial_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
