# Generated by Django 2.2 on 2019-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_voucherdetail_header_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='attn',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='currency',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='lead_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='payment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='prc_basis',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='validity',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
